---
# Development/testing config.yml
frontend:
  host: '127.0.0.1'
  port: 3000
  tls: false
backend:
  debug: true
  # The hosts ['.localhost', '127.0.0.1', '[::1]'] are automatically allowed when debug is true
  host: '127.0.0.1'
  port: 8000
  path: '/'
  tls: false
  secret_key: 'l^k&e20&r754)5zi^8%zbfus66j#ytz@%bu44(fos!&7zgbl1d'
  database:
    engine: 'sqlite3'
    # Path is relative to BASE_DIR - see settings.py in backend
    name: 'db.sqlite3'
agent:
  host: '127.0.0.1'
  debug: true
  port: 9000
  icecast:
    hostname: 'fake.icecast.example.org'
    port: 8000
    data_file: 'data/response.xml'
    stats_url: '/admin/stats'
    username: 'my_admin'
    password: 'super_secure_password'
    request_timeout: 5
  cache_ttl: 240
  data_dir: 'data'
  key: 'ih#{YxFGDk(yRtB9k%jj}gf72rfVR8Nouy4w3n?/geHz.c3num=cbP6V86B(XKDN'
