name: ci

on: [push, pull_request]

jobs:
  backend_tests:
    name: Run backend tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up dependencies
        run: sudo apt-get update && sudo apt-get install apache2-dev

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install backend dependencies
        run: pip install -r requirements.txt
        working-directory: ./backend

      - name: Set backend configuration
        run: cp config.dev.yml config.yml

      - name: Prepare migrations for backend test database
        run: python manage.py makemigrations
        working-directory: ./backend

      - name: Run tests
        run: coverage run manage.py test
        working-directory: ./backend

  frontend_tests:
    name: Run frontend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.JS
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
          check-latest: true

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run tests
        run: npm test -- --coverage --watchAll=false
        working-directory: ./frontend

  build_backend:
    name: Build backend
    runs-on: ubuntu-latest
    needs: backend_tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build backend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deploy/backend/Dockerfile
          platforms: linux/amd64
          push: false

  build_frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    needs: frontend_tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deploy/frontend/Dockerfile
          platforms: linux/amd64
          push: false
